// src/routes/analysis.js - Contractor Analytics Portal
import express from 'express';
import multer from 'multer';
import PDFDocument from 'pdfkit';
import { authenticateToken } from '../middleware/authMiddleware.js';
import { adminDb, storage } from '../config/firebase.js';
import { fetchSheetData, fetchGoogleSheetData, parseSpreadsheet, autoGenerateDashboardConfig, detectLinkType, generatePredictiveAnalysis } from '../utils/sheetAnalyzer.js';
import { forceSyncDashboard } from '../services/dashboardSyncService.js';
import Subscription from '../models/Subscription.js';

const router = express.Router();
const upload = multer({
    storage: multer.memoryStorage(),
    limits: { fileSize: 50 * 1024 * 1024 },
    fileFilter: (req, file, cb) => {
        const allowed = [
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', // .xlsx
            'application/vnd.ms-excel', // .xls
            'text/csv', // .csv
            'application/csv',
            'text/comma-separated-values',
            'application/octet-stream' // fallback for some browsers
        ];
        const ext = (file.originalname || '').toLowerCase();
        if (allowed.includes(file.mimetype) || ext.endsWith('.xlsx') || ext.endsWith('.xls') || ext.endsWith('.csv')) {
            cb(null, true);
        } else {
            cb(new Error('Unsupported file type. Please upload an Excel (.xlsx, .xls) or CSV file.'));
        }
    }
});

// ── AI ANALYSIS USAGE HELPERS ──

/**
 * Check if the user has an active AI analysis subscription and remaining quota.
 * Returns { allowed, subscription, message }.
 */
async function checkAiAnalysisQuota(userId) {
    const subscription = await Subscription.findOne({
        userId,
        plan: { $regex: /^ai_analysis_/ },
        status: { $in: ['active', 'free_override'] },
    }).sort({ createdAt: -1 });

    if (!subscription) {
        return { allowed: false, subscription: null, message: 'No active AI Analysis subscription. Please subscribe to an AI Analysis plan.' };
    }

    // Check storage cap
    if (subscription.storageAllowedMB && subscription.storageUsedMB >= subscription.storageAllowedMB) {
        return { allowed: false, subscription, message: `Storage limit reached (${(subscription.storageUsedMB / 1024).toFixed(1)} GB / ${(subscription.storageAllowedMB / 1024).toFixed(0)} GB). Please upgrade your plan.` };
    }

    // Check analysis quota
    if (subscription.aiAnalysisQuota != null && subscription.aiAnalysesUsed >= subscription.aiAnalysisQuota) {
        return { allowed: false, subscription, message: `Analysis quota reached (${subscription.aiAnalysesUsed} / ${subscription.aiAnalysisQuota}). Quota resets at the end of your billing cycle.` };
    }

    return { allowed: true, subscription, message: 'OK' };
}

/**
 * Increment analyses used counter and optionally add storage usage.
 */
async function recordAnalysisUsage(subscriptionId, storageDeltaMB = 0) {
    const update = { $inc: { aiAnalysesUsed: 1 } };
    if (storageDeltaMB > 0) {
        update.$inc.storageUsedMB = storageDeltaMB;
    }
    await Subscription.findByIdAndUpdate(subscriptionId, update);
}

// Firestore max document size is ~1MB. We aim to stay well under that.
const FIRESTORE_DOC_LIMIT = 800 * 1024; // 800KB safety margin

function estimateJsonSize(obj) {
    try {
        return Buffer.byteLength(JSON.stringify(obj), 'utf8');
    } catch {
        return Infinity;
    }
}

/**
 * Upload spreadsheet file to Firebase Storage for safekeeping.
 * Returns the storage path (data can be re-processed from this file later).
 */
async function uploadSpreadsheetToStorage(fileBuffer, originalName, userEmail) {
    try {
        const bucket = storage.bucket();
        const timestamp = Date.now();
        const safeName = originalName.replace(/[^a-zA-Z0-9._-]/g, '_');
        const storagePath = `analysis-uploads/${userEmail}/${timestamp}_${safeName}`;
        const fileRef = bucket.file(storagePath);

        await fileRef.save(fileBuffer, {
            metadata: {
                contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                metadata: { originalName, uploadedBy: userEmail, uploadedAt: new Date().toISOString() }
            },
            resumable: false
        });

        console.log(`[ANALYSIS] Spreadsheet uploaded to Storage: ${storagePath} (${(fileBuffer.length / 1024).toFixed(1)}KB)`);
        return storagePath;
    } catch (err) {
        console.error('[ANALYSIS] Storage upload failed (non-fatal):', err.message);
        return null;
    }
}

/**
 * Create lightweight chart configs: keeps chart type, columns, KPIs,
 * but limits data arrays to maxRows for Firestore storage.
 */
function createLightweightCharts(charts, maxRows = 50) {
    return charts.map(chart => ({
        ...chart,
        labels: chart.labels ? chart.labels.slice(0, maxRows) : [],
        datasets: chart.datasets ? chart.datasets.map(ds => ({
            label: ds.label,
            data: ds.data ? ds.data.slice(0, maxRows) : []
        })) : [],
        rowCount: Math.min(chart.rowCount || 0, maxRows),
        isLightweight: true
    }));
}

/**
 * Progressively trim dashboard data to GUARANTEE it fits under Firestore's document limit.
 * Removes secondary charts, trims datasets, strips predictive analysis, then strips datasets entirely.
 */
function trimToFit(dashboardData, limit) {
    let size = estimateJsonSize(dashboardData);
    if (size <= limit) return dashboardData;

    // Step 1: Remove secondary/extra charts (keep only primary per sheet)
    if (dashboardData.charts && dashboardData.charts.length > 1) {
        dashboardData.charts = dashboardData.charts.filter(c => !c.isSecondary);
        size = estimateJsonSize(dashboardData);
        if (size <= limit) return dashboardData;
    }

    // Step 2: Trim predictive analysis to minimal version (keep insights + limited forecasts)
    if (dashboardData.predictiveAnalysis) {
        dashboardData.predictiveAnalysis = {
            forecasts: (dashboardData.predictiveAnalysis.forecasts || []).slice(0, 3).map(f => ({
                sheet: f.sheet, column: f.column,
                regression: f.regression,
                values: (f.values || []).slice(0, 3),
                forecastLabels: (f.forecastLabels || []).slice(0, 3)
            })),
            correlations: dashboardData.predictiveAnalysis.correlations || null,
            anomalies: (dashboardData.predictiveAnalysis.anomalies || []).slice(0, 3).map(a => ({
                sheet: a.sheet, column: a.column,
                anomalies: (a.anomalies || []).slice(0, 5)
            })),
            insights: (dashboardData.predictiveAnalysis.insights || []).slice(0, 6),
            movingAverages: {},
            seasonality: dashboardData.predictiveAnalysis.seasonality || null
        };
        size = estimateJsonSize(dashboardData);
        if (size <= limit) return dashboardData;

        // If still too large, strip predictive analysis completely
        dashboardData.predictiveAnalysis = null;
        size = estimateJsonSize(dashboardData);
        if (size <= limit) return dashboardData;
    }

    // Step 3: Trim to 100 rows with minimal KPIs
    if (dashboardData.charts) {
        for (const chart of dashboardData.charts) {
            if (chart.labels) chart.labels = chart.labels.slice(0, 100);
            if (chart.datasets) {
                for (const ds of chart.datasets) {
                    if (ds.data) ds.data = ds.data.slice(0, 100);
                }
            }
            if (chart.kpis && chart.kpis.length > 3) chart.kpis = chart.kpis.slice(0, 3);
            chart.rowCount = Math.min(chart.rowCount || 0, 100);
        }
        size = estimateJsonSize(dashboardData);
        if (size <= limit) return dashboardData;
    }

    // Step 4: Trim to 50 rows, max 5 charts, max 4 columns per chart
    if (dashboardData.charts) {
        dashboardData.charts = dashboardData.charts.slice(0, 5);
        for (const chart of dashboardData.charts) {
            if (chart.labels) chart.labels = chart.labels.slice(0, 50);
            if (chart.datasets) {
                chart.datasets = chart.datasets.slice(0, 4);
                for (const ds of chart.datasets) {
                    if (ds.data) ds.data = ds.data.slice(0, 50);
                }
            }
            if (chart.kpis) chart.kpis = chart.kpis.slice(0, 2);
            chart.rowCount = Math.min(chart.rowCount || 0, 50);
        }
        size = estimateJsonSize(dashboardData);
        if (size <= limit) return dashboardData;
    }

    // Step 5: Keep only chart metadata (no data arrays at all)
    if (dashboardData.charts) {
        dashboardData.charts = dashboardData.charts.slice(0, 3).map(chart => ({
            sheetName: chart.sheetName,
            customTitle: chart.customTitle,
            chartType: chart.chartType,
            labelColumn: chart.labelColumn,
            dataColumns: chart.dataColumns ? chart.dataColumns.slice(0, 4) : [],
            labels: [],
            datasets: (chart.datasets || []).slice(0, 4).map(ds => ({ label: ds.label, data: [] })),
            kpis: (chart.kpis || []).slice(0, 2),
            rowCount: 0,
            isLightweight: true
        }));
        size = estimateJsonSize(dashboardData);
        if (size <= limit) return dashboardData;
    }

    // Step 6: Nuclear option — keep only 1 chart with metadata only, strip everything else
    if (dashboardData.charts) {
        dashboardData.charts = dashboardData.charts.slice(0, 1).map(chart => ({
            sheetName: chart.sheetName,
            customTitle: chart.customTitle,
            chartType: chart.chartType,
            labelColumn: chart.labelColumn,
            dataColumns: (chart.dataColumns || []).slice(0, 2),
            labels: [],
            datasets: [],
            kpis: [],
            rowCount: 0,
            isLightweight: true
        }));
    }
    dashboardData.predictiveAnalysis = null;
    dashboardData.sheetNames = (dashboardData.sheetNames || []).slice(0, 3);

    return dashboardData;
}

// Protect all routes with authentication
router.use(authenticateToken);

// GET /api/analysis/usage - Get current AI analysis subscription usage for the user
router.get('/usage', async (req, res) => {
    try {
        const userId = req.user.userId || req.user.uid || req.user.id;
        if (!userId) return res.status(400).json({ success: false, message: 'User ID not found' });

        const subscription = await Subscription.findOne({
            userId,
            plan: { $regex: /^ai_analysis_/ },
            status: { $in: ['active', 'free_override'] },
        }).sort({ createdAt: -1 });

        if (!subscription) {
            return res.json({
                success: true,
                hasSubscription: false,
                usage: null,
            });
        }

        res.json({
            success: true,
            hasSubscription: true,
            usage: {
                plan: subscription.plan,
                planLabel: subscription.planLabel,
                billingCycle: subscription.billingCycle,
                analysesUsed: subscription.aiAnalysesUsed || 0,
                analysesAllowed: subscription.aiAnalysisQuota,
                estimationUsedMB: subscription.storageUsedMB || 0,
                estimationAllowedMB: subscription.storageAllowedMB,
                estimationUsedGB: ((subscription.storageUsedMB || 0) / 1024).toFixed(2),
                estimationAllowedGB: subscription.storageAllowedMB ? (subscription.storageAllowedMB / 1024).toFixed(0) : null,
                status: subscription.status,
                endDate: subscription.endDate,
                amount: subscription.amount,
            },
        });
    } catch (error) {
        console.error('[ANALYSIS] Error fetching usage:', error);
        res.status(500).json({ success: false, message: 'Failed to fetch usage data' });
    }
});

// === CONTRACTOR SHEET UPLOAD - Auto-generates dashboard, sends to admin for approval ===
// Supports: file upload (.xlsx, .xls, .csv) AND/OR Google Sheet link
// POST /api/analysis/upload-sheet
router.post('/upload-sheet', (req, res, next) => {
    upload.single('spreadsheet')(req, res, (err) => {
        if (err) {
            if (err.code === 'LIMIT_FILE_SIZE') {
                return res.status(413).json({ success: false, message: 'File exceeds 50MB limit. Please use a smaller file.' });
            }
            if (err.message && err.message.includes('Unsupported file type')) {
                return res.status(400).json({ success: false, message: err.message });
            }
            return res.status(400).json({ success: false, message: 'File upload failed: ' + (err.message || 'Unknown error') });
        }
        next();
    });
}, async (req, res) => {
    try {
        const userEmail = req.user.email;
        const userName = req.user.name || req.user.displayName || 'Unknown User';

        if (!userEmail) {
            return res.status(400).json({ success: false, message: 'User email not found' });
        }

        const { title, frequency, description, dataType, googleSheetUrl, syncInterval } = req.body;
        const hasFile = !!req.file;
        const hasLink = !!(googleSheetUrl && googleSheetUrl.trim());

        if (!hasFile && !hasLink) {
            return res.status(400).json({ success: false, message: 'Please upload a spreadsheet file (.xlsx, .xls, .csv) or provide a Google Sheet link' });
        }

        let sheets = {};
        let sheetNames = [];
        let dashboardCharts = [];
        let fileName = '';
        let fileSize = 0;
        let chartsGenerated = 0;

        // ── FILE UPLOAD PATH: parse, generate charts, store lightweight in Firestore ──
        if (hasFile) {
            sheets = parseSpreadsheet(req.file.buffer, req.file.originalname);
            sheetNames = Object.keys(sheets);
            fileName = req.file.originalname;
            fileSize = req.file.size;

            if (sheetNames.length === 0) {
                return res.status(400).json({ success: false, message: 'No valid data found in the uploaded file. Please check your spreadsheet.' });
            }

            dashboardCharts = autoGenerateDashboardConfig(sheets, frequency || 'daily');

            if (dashboardCharts.length === 0) {
                return res.status(400).json({ success: false, message: 'Could not extract numeric data from the spreadsheet. Ensure columns have numeric values.' });
            }

            chartsGenerated = dashboardCharts.length;

            // Upload original file to Firebase Storage for safekeeping
            let storagePath = null;
            try {
                storagePath = await uploadSpreadsheetToStorage(req.file.buffer, req.file.originalname, userEmail);
            } catch (e) { /* non-fatal */ }

            // Generate lightweight predictive analysis
            let predictiveForStorage = null;
            try {
                const pa = generatePredictiveAnalysis(sheets, dashboardCharts);
                predictiveForStorage = {
                    forecasts: (pa.forecasts || []).slice(0, 5),
                    correlations: pa.correlations || null,
                    anomalies: (pa.anomalies || []).slice(0, 5),
                    insights: (pa.insights || []).slice(0, 15),
                    movingAverages: {},
                    seasonality: pa.seasonality || null
                };
            } catch (paErr) {
                console.error('[ANALYSIS] Predictive analysis error (non-fatal):', paErr.message);
            }

            let dashboardData = {
                title: title || `Dashboard - ${fileName}`,
                description: description || '',
                dataType: dataType || 'Production Update',
                contractorEmail: userEmail,
                contractorName: userName,
                frequency: frequency || 'daily',
                fileName, fileSize,
                storagePath: storagePath || null,
                googleSheetUrl: null, linkType: null,
                syncInterval: 'manual', lastSyncedAt: null, lastSyncStatus: null,
                sheetNames,
                charts: createLightweightCharts(dashboardCharts, 100),
                totalChartsGenerated: chartsGenerated,
                predictiveAnalysis: predictiveForStorage,
                dataSource: 'file',
                status: 'pending', uploadedBy: 'contractor', createdBy: userEmail,
                createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
                approvedAt: null, approvedBy: null
            };

            dashboardData = trimToFit(dashboardData, FIRESTORE_DOC_LIMIT);
            let estimatedSize = estimateJsonSize(dashboardData);
            console.log(`[ANALYSIS] File dashboard size after trim: ~${(estimatedSize / 1024).toFixed(1)}KB`);

            // Safety: if still over limit after trimToFit, aggressively strip data
            if (estimatedSize > FIRESTORE_DOC_LIMIT) {
                console.warn(`[ANALYSIS] Dashboard still over limit (${(estimatedSize / 1024).toFixed(1)}KB), applying emergency trim`);
                dashboardData.charts = (dashboardData.charts || []).slice(0, 2).map(c => ({
                    sheetName: c.sheetName, customTitle: c.customTitle, chartType: c.chartType,
                    labelColumn: c.labelColumn, dataColumns: (c.dataColumns || []).slice(0, 3),
                    labels: [], datasets: [], kpis: [], rowCount: 0, isLightweight: true
                }));
                dashboardData.predictiveAnalysis = null;
                dashboardData.sheetNames = (dashboardData.sheetNames || []).slice(0, 5);
                estimatedSize = estimateJsonSize(dashboardData);
                console.log(`[ANALYSIS] After emergency trim: ~${(estimatedSize / 1024).toFixed(1)}KB`);
            }

            let docRef;
            try {
                docRef = await adminDb.collection('dashboards').add(dashboardData);
            } catch (firestoreErr) {
                // If Firestore still rejects, try one more time with minimal data
                if (firestoreErr.message && (firestoreErr.message.includes('too large') || firestoreErr.message.includes('exceeds') || firestoreErr.message.includes('INVALID_ARGUMENT'))) {
                    console.warn('[ANALYSIS] Firestore save failed, retrying with minimal data');
                    dashboardData.charts = [];
                    dashboardData.predictiveAnalysis = null;
                    docRef = await adminDb.collection('dashboards').add(dashboardData);
                } else {
                    throw firestoreErr;
                }
            }
            console.log(`[ANALYSIS] Contractor ${userEmail} uploaded file -> Dashboard ${docRef.id} (pending)`);

            return res.json({
                success: true,
                message: `Dashboard auto-generated with ${chartsGenerated} charts from uploaded file! Sent to admin for approval.`,
                dashboardId: docRef.id,
                chartsGenerated,
                sheetsProcessed: sheetNames.length
            });
        }

        // ── LINK UPLOAD PATH: validate link, store ONLY metadata (no chart data) ──
        // Sheet data is fetched on-demand via /live-data endpoint to avoid Firestore size limits
        if (hasLink) {
            const trimmedUrl = googleSheetUrl.trim();
            const linkType = detectLinkType(trimmedUrl);
            console.log(`[ANALYSIS] Link upload (${linkType}): ${trimmedUrl.substring(0, 80)}...`);

            // Quick validation: try to fetch the sheet to confirm the link works
            try {
                const result = await fetchSheetData(trimmedUrl);
                sheetNames = result.sheetNames;
                // Count how many charts would be generated (for the response message)
                const previewCharts = autoGenerateDashboardConfig(result.sheets, frequency || 'daily');
                chartsGenerated = previewCharts.length;
                fileName = linkType === 'google' ? 'Google Sheet' : linkType === 'sharepoint' ? 'SharePoint File' : 'Linked Sheet';

                if (chartsGenerated === 0) {
                    return res.status(400).json({ success: false, message: 'Could not extract numeric data from the linked sheet. Ensure it contains columns with numeric values.' });
                }
                console.log(`[ANALYSIS] Link validated: ${sheetNames.length} sheets, ${chartsGenerated} charts possible`);
            } catch (sheetError) {
                console.error('[ANALYSIS] Sheet fetch error:', sheetError.message);
                return res.status(400).json({ success: false, message: sheetError.message });
            }

            // Store ONLY metadata + link in Firestore (tiny document, never exceeds size limit)
            const dashboardData = {
                title: title || `Dashboard - ${fileName}`,
                description: description || '',
                dataType: dataType || 'Production Update',
                contractorEmail: userEmail,
                contractorName: userName,
                frequency: frequency || 'daily',
                fileName, fileSize: 0,
                storagePath: null,
                googleSheetUrl: trimmedUrl,
                linkType,
                syncInterval: syncInterval || 'daily',
                lastSyncedAt: new Date().toISOString(),
                lastSyncStatus: 'success',
                sheetNames,
                charts: [],
                totalChartsGenerated: chartsGenerated,
                predictiveAnalysis: null,
                dataSource: 'link',
                status: 'pending', uploadedBy: 'contractor', createdBy: userEmail,
                createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
                approvedAt: null, approvedBy: null
            };

            const docRef = await adminDb.collection('dashboards').add(dashboardData);
            console.log(`[ANALYSIS] Contractor ${userEmail} linked ${linkType} sheet -> Dashboard ${docRef.id} (pending, data on-demand)`);

            const syncMsg = syncInterval !== 'manual' ? ` Auto-sync: ${syncInterval}.` : '';
            return res.json({
                success: true,
                message: `Dashboard linked with ${chartsGenerated} charts from ${fileName}! Sent to admin for approval.${syncMsg}`,
                dashboardId: docRef.id,
                chartsGenerated,
                sheetsProcessed: sheetNames.length
            });
        }

    } catch (error) {
        console.error('[ANALYSIS] Sheet upload error:', error.message, error.stack);
        const msg = (error.message || '').toLowerCase();
        if (msg.includes('exceeds the maximum allowed size') || msg.includes('invalid_argument') || msg.includes('too large') || msg.includes('document size')) {
            res.status(400).json({ success: false, message: 'Your spreadsheet has too many sheets or columns. Try uploading a file with fewer sheets (max 5) or fewer columns.' });
        } else if (msg.includes('cfb') || msg.includes('corrupted') || msg.includes('unsupported') || msg.includes('file type')) {
            res.status(400).json({ success: false, message: 'Could not read this file. Please ensure it is a valid .xlsx, .xls, or .csv file.' });
        } else if (msg.includes('timeout') || msg.includes('abort') || msg.includes('econnreset')) {
            res.status(504).json({ success: false, message: 'The request timed out while processing your data. Try a smaller file or fewer sheets.' });
        } else if (msg.includes('not publicly shared') || msg.includes('requires authentication') || msg.includes('permission')) {
            res.status(400).json({ success: false, message: error.message });
        } else if (msg.includes('payload too large') || msg.includes('entity too large') || msg.includes('request entity')) {
            res.status(413).json({ success: false, message: 'File is too large to upload. Maximum file size is 50MB.' });
        } else {
            res.status(500).json({ success: false, message: 'Failed to process your data. Please try again or upload a smaller file.' });
        }
    }
});

// GET /api/analysis/my-dashboards - Get all dashboards for this contractor (pending + approved + rejected)
router.get('/my-dashboards', async (req, res) => {
    try {
        const userEmail = req.user.email;
        if (!userEmail) return res.status(400).json({ success: false, message: 'User email not found' });

        const snapshot = await adminDb.collection('dashboards')
            .where('contractorEmail', '==', userEmail)
            .get();

        const dashboards = snapshot.docs.map(doc => {
            const d = doc.data();
            return {
                _id: doc.id,
                title: d.title,
                description: d.description,
                dataType: d.dataType || 'Production Update',
                frequency: d.frequency,
                fileName: d.fileName,
                googleSheetUrl: d.googleSheetUrl || null,
                linkType: d.linkType || null,
                syncInterval: d.syncInterval || 'manual',
                lastSyncedAt: d.lastSyncedAt || null,
                lastSyncStatus: d.lastSyncStatus || null,
                manualDashboardUrl: d.manualDashboardUrl || null,
                dataSource: d.dataSource || (d.googleSheetUrl ? 'link' : 'file'),
                status: d.status,
                chartsCount: d.totalChartsGenerated || (d.charts || []).length,
                charts: d.status === 'approved' ? d.charts : null,
                predictiveAnalysis: d.status === 'approved' ? (d.predictiveAnalysis || null) : null,
                reportType: d.reportType || 'auto',
                pdfReport: d.pdfReport ? { originalName: d.pdfReport.originalName, fileSize: d.pdfReport.fileSize } : null,
                htmlReport: d.htmlReport ? { originalName: d.htmlReport.originalName, fileSize: d.htmlReport.fileSize, isTemplate: d.htmlReport.isTemplate } : null,
                lastDataUploadAt: d.lastDataUploadAt || null,
                sheetNames: d.sheetNames,
                createdAt: d.createdAt,
                approvedAt: d.approvedAt,
                updatedAt: d.updatedAt
            };
        });

        dashboards.sort((a, b) => new Date(b.approvedAt || b.createdAt) - new Date(a.approvedAt || a.createdAt));

        res.json({ success: true, dashboards });
    } catch (error) {
        console.error('[ANALYSIS] Error fetching my-dashboards:', error);
        res.status(500).json({ success: false, message: 'Failed to fetch dashboards' });
    }
});

// POST /api/analysis/dashboard/:id/sync - Force re-sync a dashboard from its linked sheet
router.post('/dashboard/:id/sync', async (req, res) => {
    try {
        const userEmail = req.user.email;
        const doc = await adminDb.collection('dashboards').doc(req.params.id).get();
        if (!doc.exists) return res.status(404).json({ success: false, message: 'Dashboard not found' });

        const data = doc.data();
        if (data.contractorEmail !== userEmail) {
            return res.status(403).json({ success: false, message: 'Access denied' });
        }
        if (!data.googleSheetUrl) {
            return res.status(400).json({ success: false, message: 'Dashboard has no linked sheet URL to sync from' });
        }

        const result = await forceSyncDashboard(req.params.id);
        res.json(result);
    } catch (error) {
        console.error('[ANALYSIS] Sync error:', error.message);
        res.status(500).json({ success: false, message: error.message || 'Failed to sync dashboard' });
    }
});

// DELETE /api/analysis/dashboard/:id - Contractor can delete their own pending dashboard
router.delete('/dashboard/:id', async (req, res) => {
    try {
        const userEmail = req.user.email;
        const doc = await adminDb.collection('dashboards').doc(req.params.id).get();
        if (!doc.exists) return res.status(404).json({ success: false, message: 'Dashboard not found' });

        const data = doc.data();
        if (data.contractorEmail !== userEmail) {
            return res.status(403).json({ success: false, message: 'Access denied' });
        }
        if (data.status !== 'pending') {
            return res.status(400).json({ success: false, message: 'Can only delete pending dashboards' });
        }

        await adminDb.collection('dashboards').doc(req.params.id).delete();
        res.json({ success: true, message: 'Dashboard deleted successfully' });
    } catch (error) {
        console.error('[ANALYSIS] Error deleting dashboard:', error);
        res.status(500).json({ success: false, message: 'Failed to delete dashboard' });
    }
});

// GET /api/analysis/dashboard/:id/live-data - Fetch fresh chart data on-demand
// For link-based dashboards: fetches from the linked sheet URL
// For file-based dashboards with stripped data: regenerates from Firebase Storage
router.get('/dashboard/:id/live-data', async (req, res) => {
    try {
        const userEmail = req.user.email;
        const doc = await adminDb.collection('dashboards').doc(req.params.id).get();
        if (!doc.exists) return res.status(404).json({ success: false, message: 'Dashboard not found' });

        const data = doc.data();
        if (data.contractorEmail !== userEmail) {
            return res.status(403).json({ success: false, message: 'Access denied' });
        }

        // For file-based dashboards: regenerate charts from Firebase Storage
        if (!data.googleSheetUrl && data.storagePath) {
            console.log(`[ANALYSIS] Regenerating charts from Storage for dashboard ${req.params.id}: ${data.storagePath}`);
            try {
                const bucket = storage.bucket();
                const fileRef = bucket.file(data.storagePath);
                const [fileBuffer] = await fileRef.download();
                const fileName = data.fileName || data.storagePath.split('/').pop() || 'file.xlsx';
                const sheets = parseSpreadsheet(fileBuffer, fileName);
                const charts = autoGenerateDashboardConfig(sheets, data.frequency || 'daily');

                let predictiveAnalysis = null;
                try {
                    predictiveAnalysis = generatePredictiveAnalysis(sheets, charts);
                } catch (e) { /* non-fatal */ }

                return res.json({
                    success: true,
                    charts,
                    sheetNames: Object.keys(sheets),
                    predictiveAnalysis,
                    fetchedAt: new Date().toISOString(),
                    regeneratedFromStorage: true
                });
            } catch (storageErr) {
                console.error('[ANALYSIS] Storage regeneration error:', storageErr.message);
                return res.status(500).json({ success: false, message: 'Failed to regenerate charts from stored file' });
            }
        }

        if (!data.googleSheetUrl) {
            return res.status(400).json({ success: false, message: 'Dashboard has no linked sheet URL or stored file' });
        }

        console.log(`[ANALYSIS] Fetching live data for dashboard ${req.params.id} from: ${data.googleSheetUrl.substring(0, 60)}...`);
        const result = await fetchSheetData(data.googleSheetUrl);
        const charts = autoGenerateDashboardConfig(result.sheets, data.frequency || 'daily');

        let predictiveAnalysis = null;
        try {
            predictiveAnalysis = generatePredictiveAnalysis(result.sheets, charts);
        } catch (e) { /* non-fatal */ }

        res.json({
            success: true,
            charts,
            sheetNames: result.sheetNames,
            predictiveAnalysis,
            fetchedAt: new Date().toISOString()
        });
    } catch (error) {
        console.error('[ANALYSIS] Live data fetch error:', error.message);
        res.status(500).json({ success: false, message: error.message || 'Failed to fetch live data from sheet' });
    }
});

// === LEGACY ENDPOINTS (kept for backwards compatibility) ===

// GET /api/analysis/my-request - Get contractor's analysis request
router.get('/my-request', async (req, res) => {
    try {
        const userEmail = req.user.email;
        if (!userEmail) {
            return res.status(400).json({ success: false, message: 'User email not found' });
        }

        const snapshot = await adminDb.collection('analysis_requests')
            .where('contractorEmail', '==', userEmail)
            .orderBy('createdAt', 'desc')
            .limit(1)
            .get();

        if (snapshot.empty) {
            return res.json({ success: true, request: null });
        }

        const doc = snapshot.docs[0];
        const data = doc.data();

        res.json({
            success: true,
            request: {
                _id: doc.id,
                dataType: data.dataType || 'Production Update',
                frequency: data.frequency || 'Daily',
                description: data.description || '',
                googleSheetUrl: data.googleSheetUrl || '',
                vercelUrl: data.vercelUrl || null,
                status: data.vercelUrl ? 'completed' : 'pending',
                adminNotes: data.adminNotes || '',
                createdAt: data.createdAt,
                updatedAt: data.updatedAt
            }
        });
    } catch (error) {
        console.error('[ANALYSIS] Error fetching contractor request:', error);
        res.status(500).json({ success: false, message: 'Failed to fetch analysis request' });
    }
});

// POST /api/analysis/submit-request - Submit new analysis request (legacy)
router.post('/submit-request', async (req, res) => {
    try {
        const { dataType, frequency, googleSheetUrl, description } = req.body;
        const userEmail = req.user.email;
        const userName = req.user.name || req.user.displayName || 'Unknown User';
        const userId = req.user.uid || req.user.id || null;

        if (!googleSheetUrl || !description) {
            return res.status(400).json({ success: false, message: 'Data source URL and description are required' });
        }
        if (!userEmail) {
            return res.status(400).json({ success: false, message: 'User email is required' });
        }
        if (!googleSheetUrl.includes('http')) {
            return res.status(400).json({ success: false, message: 'Please provide a valid URL' });
        }

        const existingSnapshot = await adminDb.collection('analysis_requests')
            .where('contractorEmail', '==', userEmail)
            .where('vercelUrl', '==', null)
            .get();

        if (!existingSnapshot.empty) {
            return res.status(400).json({ success: false, message: 'You already have a pending analysis request' });
        }

        const requestData = {
            contractorEmail: userEmail,
            contractorName: userName,
            dataType: dataType || 'Production Update',
            frequency: frequency || 'Daily',
            googleSheetUrl: googleSheetUrl,
            description: description,
            vercelUrl: null,
            adminNotes: '',
            status: 'pending',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        };

        if (userId) requestData.contractorId = userId;

        const docRef = await adminDb.collection('analysis_requests').add(requestData);

        res.json({ success: true, message: 'Business analytics request submitted successfully', requestId: docRef.id });
    } catch (error) {
        console.error('[ANALYSIS] Error submitting request:', error);
        res.status(500).json({ success: false, message: 'Failed to submit business analytics request' });
    }
});

// PUT /api/analysis/request/:requestId - Update analysis request
router.put('/request/:requestId', async (req, res) => {
    try {
        const { requestId } = req.params;
        const { dataType, frequency, googleSheetUrl, description } = req.body;
        const userEmail = req.user.email;

        if (!userEmail) return res.status(400).json({ success: false, message: 'User email is required' });

        const requestDoc = await adminDb.collection('analysis_requests').doc(requestId).get();
        if (!requestDoc.exists) return res.status(404).json({ success: false, message: 'Analysis request not found' });

        const requestData = requestDoc.data();
        if (requestData.contractorEmail !== userEmail) return res.status(403).json({ success: false, message: 'Not authorized' });
        if (requestData.vercelUrl) return res.status(400).json({ success: false, message: 'Cannot update after report has been uploaded' });

        await adminDb.collection('analysis_requests').doc(requestId).update({
            dataType: dataType || requestData.dataType,
            frequency: frequency || requestData.frequency,
            googleSheetUrl: googleSheetUrl || requestData.googleSheetUrl,
            description: description || requestData.description,
            updatedAt: new Date().toISOString()
        });

        res.json({ success: true, message: 'Business analytics request updated successfully' });
    } catch (error) {
        console.error('[ANALYSIS] Error updating request:', error);
        res.status(500).json({ success: false, message: 'Failed to update business analytics request' });
    }
});

// DELETE /api/analysis/request/:requestId - Cancel analysis request
router.delete('/request/:requestId', async (req, res) => {
    try {
        const { requestId } = req.params;
        const userEmail = req.user.email;

        if (!userEmail) return res.status(400).json({ success: false, message: 'User email is required' });

        const requestDoc = await adminDb.collection('analysis_requests').doc(requestId).get();
        if (!requestDoc.exists) return res.status(404).json({ success: false, message: 'Request not found' });

        const requestData = requestDoc.data();
        if (requestData.contractorEmail !== userEmail) return res.status(403).json({ success: false, message: 'Not authorized' });

        await adminDb.collection('analysis_requests').doc(requestId).delete();
        res.json({ success: true, message: 'Request cancelled successfully' });
    } catch (error) {
        console.error('[ANALYSIS] Error cancelling request:', error);
        res.status(500).json({ success: false, message: 'Failed to cancel request' });
    }
});

// GET /api/analysis/history - Get contractor's analysis history
router.get('/history', async (req, res) => {
    try {
        const userEmail = req.user.email;
        if (!userEmail) return res.status(400).json({ success: false, message: 'User email is required' });

        const snapshot = await adminDb.collection('analysis_requests')
            .where('contractorEmail', '==', userEmail)
            .orderBy('createdAt', 'desc')
            .get();

        const requests = snapshot.docs.map(doc => {
            const data = doc.data();
            return {
                _id: doc.id, dataType: data.dataType || 'Production Update',
                frequency: data.frequency || 'Daily', description: data.description || '',
                googleSheetUrl: data.googleSheetUrl || '', vercelUrl: data.vercelUrl || null,
                status: data.vercelUrl ? 'completed' : 'pending',
                createdAt: data.createdAt, updatedAt: data.updatedAt
            };
        });

        res.json({ success: true, requests });
    } catch (error) {
        console.error('[ANALYSIS] Error fetching history:', error);
        res.status(500).json({ success: false, message: 'Failed to fetch history' });
    }
});

// === USER DATA UPLOAD WITH HTML TEMPLATE AUTO-UPDATE ===

// POST /api/analysis/dashboard/:id/upload-data - User uploads new data, auto-updates report using HTML template
// When admin has set an HTML template and user uploads new Excel/CSV data, the report auto-updates
router.post('/dashboard/:id/upload-data', (req, res, next) => {
    upload.single('spreadsheet')(req, res, (err) => {
        if (err) {
            if (err.code === 'LIMIT_FILE_SIZE') return res.status(413).json({ success: false, message: 'File exceeds 50MB limit.' });
            return res.status(400).json({ success: false, message: 'File upload failed: ' + (err.message || 'Unknown error') });
        }
        next();
    });
}, async (req, res) => {
    try {
        const userEmail = req.user.email;
        const doc = await adminDb.collection('dashboards').doc(req.params.id).get();
        if (!doc.exists) return res.status(404).json({ success: false, message: 'Dashboard not found' });

        const data = doc.data();
        if (data.contractorEmail !== userEmail) {
            return res.status(403).json({ success: false, message: 'Access denied' });
        }
        if (data.status !== 'approved') {
            return res.status(400).json({ success: false, message: 'Dashboard must be approved before uploading data' });
        }

        const hasFile = !!req.file;
        const { googleSheetUrl } = req.body;
        const hasLink = !!(googleSheetUrl && googleSheetUrl.trim());

        if (!hasFile && !hasLink) {
            return res.status(400).json({ success: false, message: 'Please upload a spreadsheet or provide a sheet link' });
        }

        let sheets = {};
        let sheetNames = [];
        let dashboardCharts = [];

        if (hasFile) {
            sheets = parseSpreadsheet(req.file.buffer, req.file.originalname);
            sheetNames = Object.keys(sheets);
            if (sheetNames.length === 0) {
                return res.status(400).json({ success: false, message: 'No valid data found in the uploaded file.' });
            }
            dashboardCharts = autoGenerateDashboardConfig(sheets, data.frequency || 'daily');

            // Upload new file to Firebase Storage
            let storagePath = null;
            try {
                storagePath = await uploadSpreadsheetToStorage(req.file.buffer, req.file.originalname, userEmail);
            } catch (e) { /* non-fatal */ }

            const updateData = {
                fileName: req.file.originalname,
                fileSize: req.file.size,
                storagePath: storagePath || data.storagePath,
                dataSource: 'file',
                sheetNames,
                updatedAt: new Date().toISOString(),
                lastDataUploadAt: new Date().toISOString(),
                lastDataUploadBy: userEmail
            };

            // If dashboard has HTML template, keep reportType as 'html' - the template renders with new data
            // If it has auto-generated charts, update those
            if (data.reportType !== 'html' && data.reportType !== 'pdf') {
                updateData.charts = createLightweightCharts(dashboardCharts, 100);
                updateData.totalChartsGenerated = dashboardCharts.length;
                try {
                    const pa = generatePredictiveAnalysis(sheets, dashboardCharts);
                    updateData.predictiveAnalysis = {
                        forecasts: (pa.forecasts || []).slice(0, 5),
                        correlations: pa.correlations || null,
                        anomalies: (pa.anomalies || []).slice(0, 5),
                        insights: (pa.insights || []).slice(0, 15),
                        movingAverages: {},
                        seasonality: pa.seasonality || null
                    };
                } catch (e) { /* non-fatal */ }
            }

            // For HTML templates, store parsed data for template rendering
            if (data.reportType === 'html') {
                // Convert sheet data to JSON for HTML template injection
                const templateData = {};
                for (const [name, rows] of Object.entries(sheets)) {
                    templateData[name] = rows.slice(0, 1000); // limit rows for storage
                }
                updateData.templateData = templateData;
                updateData.templateDataUpdatedAt = new Date().toISOString();
            }

            await adminDb.collection('dashboards').doc(req.params.id).update(updateData);

            const isHtmlTemplate = data.reportType === 'html';
            console.log(`[ANALYSIS] User ${userEmail} uploaded new data for dashboard ${req.params.id} (${isHtmlTemplate ? 'HTML auto-update' : 'chart refresh'})`);
            return res.json({
                success: true,
                message: isHtmlTemplate
                    ? `Data uploaded! Your HTML report has been auto-updated with ${sheetNames.length} sheet(s).`
                    : `Data uploaded! Dashboard refreshed with ${dashboardCharts.length} charts.`,
                chartsGenerated: dashboardCharts.length,
                sheetsProcessed: sheetNames.length,
                autoUpdated: isHtmlTemplate
            });
        }

        if (hasLink) {
            const trimmedUrl = googleSheetUrl.trim();
            await adminDb.collection('dashboards').doc(req.params.id).update({
                googleSheetUrl: trimmedUrl,
                linkType: detectLinkType(trimmedUrl),
                dataSource: 'link',
                lastSyncedAt: new Date().toISOString(),
                lastDataUploadAt: new Date().toISOString(),
                lastDataUploadBy: userEmail,
                updatedAt: new Date().toISOString()
            });

            console.log(`[ANALYSIS] User ${userEmail} updated sheet link for dashboard ${req.params.id}`);
            return res.json({
                success: true,
                message: 'Sheet link updated! Dashboard will auto-refresh with latest data.',
                autoUpdated: data.reportType === 'html'
            });
        }
    } catch (error) {
        console.error('[ANALYSIS] Data upload error:', error);
        res.status(500).json({ success: false, message: 'Failed to upload data' });
    }
});

// GET /api/analysis/dashboard/:id/html-report - Get HTML report with injected data for rendering
router.get('/dashboard/:id/html-report', async (req, res) => {
    try {
        const userEmail = req.user.email;
        const doc = await adminDb.collection('dashboards').doc(req.params.id).get();
        if (!doc.exists) return res.status(404).json({ success: false, message: 'Dashboard not found' });

        const data = doc.data();
        if (data.contractorEmail !== userEmail) {
            return res.status(403).json({ success: false, message: 'Access denied' });
        }
        if (data.status !== 'approved') {
            return res.status(403).json({ success: false, message: 'Dashboard not approved' });
        }
        if (data.reportType !== 'html' || !data.htmlReport) {
            return res.status(400).json({ success: false, message: 'No HTML report available' });
        }

        let htmlContent = data.htmlReport.htmlContent;

        // If no inline content, fetch from storage
        if (!htmlContent && data.htmlReport.storagePath) {
            const bucket = storage.bucket();
            const fileRef = bucket.file(data.htmlReport.storagePath);
            const [fileBuffer] = await fileRef.download();
            htmlContent = fileBuffer.toString('utf-8');
        }

        if (!htmlContent) {
            return res.status(404).json({ success: false, message: 'HTML report content not found' });
        }

        // Inject template data if available (from user's latest data upload)
        let templateData = data.templateData || null;

        // If no template data but has stored spreadsheet, parse it
        if (!templateData && data.storagePath) {
            try {
                const bucket = storage.bucket();
                const fileRef = bucket.file(data.storagePath);
                const [fileBuffer] = await fileRef.download();
                const fileName = data.fileName || 'file.xlsx';
                const sheets = parseSpreadsheet(fileBuffer, fileName);
                templateData = {};
                for (const [name, rows] of Object.entries(sheets)) {
                    templateData[name] = rows.slice(0, 1000);
                }
            } catch (e) {
                console.error('[ANALYSIS] Failed to parse stored spreadsheet for template:', e.message);
            }
        }

        // If no template data but has linked sheet, fetch it
        if (!templateData && data.googleSheetUrl) {
            try {
                const result = await fetchSheetData(data.googleSheetUrl);
                templateData = {};
                for (const [name, rows] of Object.entries(result.sheets)) {
                    templateData[name] = rows.slice(0, 1000);
                }
            } catch (e) {
                console.error('[ANALYSIS] Failed to fetch sheet for template:', e.message);
            }
        }

        // Inject data into HTML template via a script tag
        if (templateData) {
            const dataScript = `<script>window.__REPORT_DATA__ = ${JSON.stringify(templateData)}; window.__REPORT_META__ = ${JSON.stringify({ title: data.title, frequency: data.frequency, updatedAt: data.templateDataUpdatedAt || data.updatedAt })};</script>`;
            // Insert before </head> or at the start of <body> or at the beginning
            if (htmlContent.includes('</head>')) {
                htmlContent = htmlContent.replace('</head>', dataScript + '</head>');
            } else if (htmlContent.includes('<body')) {
                htmlContent = htmlContent.replace(/<body[^>]*>/, (match) => match + dataScript);
            } else {
                htmlContent = dataScript + htmlContent;
            }
        }

        res.json({
            success: true,
            htmlContent,
            templateData: templateData ? true : false,
            title: data.title,
            lastDataUpdate: data.templateDataUpdatedAt || data.updatedAt
        });
    } catch (error) {
        console.error('[ANALYSIS] HTML report error:', error);
        res.status(500).json({ success: false, message: 'Failed to get HTML report' });
    }
});

// GET /api/analysis/dashboard/:id/pdf-report - Get signed URL for PDF report
router.get('/dashboard/:id/pdf-report', async (req, res) => {
    try {
        const userEmail = req.user.email;
        const doc = await adminDb.collection('dashboards').doc(req.params.id).get();
        if (!doc.exists) return res.status(404).json({ success: false, message: 'Dashboard not found' });

        const data = doc.data();
        if (data.contractorEmail !== userEmail) {
            return res.status(403).json({ success: false, message: 'Access denied' });
        }
        if (data.status !== 'approved') {
            return res.status(403).json({ success: false, message: 'Dashboard not approved' });
        }
        if (data.reportType !== 'pdf' || !data.pdfReport) {
            return res.status(400).json({ success: false, message: 'No PDF report available' });
        }

        const bucket = storage.bucket();
        const fileRef = bucket.file(data.pdfReport.storagePath);
        const [signedUrl] = await fileRef.getSignedUrl({ action: 'read', expires: Date.now() + 7 * 24 * 60 * 60 * 1000 });

        res.json({
            success: true,
            signedUrl,
            originalName: data.pdfReport.originalName,
            title: data.title
        });
    } catch (error) {
        console.error('[ANALYSIS] PDF report error:', error);
        res.status(500).json({ success: false, message: 'Failed to get PDF report' });
    }
});

// === CLIENT DASHBOARD ENDPOINTS ===

// GET /api/analysis/dashboards - Get all approved dashboards for the logged-in contractor
router.get('/dashboards', async (req, res) => {
    try {
        const userEmail = req.user.email;
        if (!userEmail) return res.status(400).json({ success: false, message: 'User email not found' });

        const snapshot = await adminDb.collection('dashboards')
            .where('contractorEmail', '==', userEmail)
            .where('status', '==', 'approved')
            .get();

        const dashboards = snapshot.docs.map(doc => {
            const d = doc.data();
            return {
                _id: doc.id, title: d.title, description: d.description,
                frequency: d.frequency, charts: d.charts, sheetNames: d.sheetNames,
                predictiveAnalysis: d.predictiveAnalysis || null,
                manualDashboardUrl: d.manualDashboardUrl || null,
                googleSheetUrl: d.googleSheetUrl || null,
                dataSource: d.dataSource || (d.googleSheetUrl ? 'link' : 'file'),
                totalChartsGenerated: d.totalChartsGenerated || (d.charts || []).length,
                reportType: d.reportType || 'auto',
                pdfReport: d.pdfReport ? { originalName: d.pdfReport.originalName, fileSize: d.pdfReport.fileSize } : null,
                htmlReport: d.htmlReport ? { originalName: d.htmlReport.originalName, fileSize: d.htmlReport.fileSize, isTemplate: d.htmlReport.isTemplate } : null,
                templateData: d.templateData ? true : false,
                lastDataUploadAt: d.lastDataUploadAt || null,
                createdAt: d.createdAt, approvedAt: d.approvedAt
            };
        });

        dashboards.sort((a, b) => new Date(b.approvedAt || b.createdAt) - new Date(a.approvedAt || a.createdAt));
        res.json({ success: true, dashboards });
    } catch (error) {
        console.error('[ANALYSIS] Error fetching client dashboards:', error);
        res.status(500).json({ success: false, message: 'Failed to fetch dashboards' });
    }
});

// GET /api/analysis/dashboards/:id - Get single dashboard full data (approved only)
router.get('/dashboards/:id', async (req, res) => {
    try {
        const userEmail = req.user.email;
        const doc = await adminDb.collection('dashboards').doc(req.params.id).get();
        if (!doc.exists) return res.status(404).json({ success: false, message: 'Dashboard not found' });

        const data = doc.data();
        if (data.contractorEmail !== userEmail) return res.status(403).json({ success: false, message: 'Access denied' });
        if (data.status !== 'approved') return res.status(403).json({ success: false, message: 'Dashboard not yet approved' });

        res.json({
            success: true,
            dashboard: {
                _id: doc.id, title: data.title, description: data.description,
                frequency: data.frequency, charts: data.charts, sheetNames: data.sheetNames,
                manualDashboardUrl: data.manualDashboardUrl || null,
                predictiveAnalysis: data.predictiveAnalysis || null,
                dataSource: data.dataSource || (data.googleSheetUrl ? 'link' : 'file'),
                googleSheetUrl: data.googleSheetUrl || null,
                linkType: data.linkType || null,
                syncInterval: data.syncInterval || 'manual',
                lastSyncedAt: data.lastSyncedAt || null,
                lastSyncStatus: data.lastSyncStatus || null,
                reportType: data.reportType || 'auto',
                pdfReport: data.pdfReport ? { originalName: data.pdfReport.originalName, fileSize: data.pdfReport.fileSize } : null,
                htmlReport: data.htmlReport ? { originalName: data.htmlReport.originalName, fileSize: data.htmlReport.fileSize, isTemplate: data.htmlReport.isTemplate } : null,
                lastDataUploadAt: data.lastDataUploadAt || null,
                createdAt: data.createdAt, approvedAt: data.approvedAt
            }
        });
    } catch (error) {
        console.error('[ANALYSIS] Error fetching dashboard:', error);
        res.status(500).json({ success: false, message: 'Failed to fetch dashboard' });
    }
});

// GET /api/analysis/dashboard/:id/download-pdf - Generate and download PDF from HTML report data
router.get('/dashboard/:id/download-pdf', authenticateToken, async (req, res) => {
    try {
        const userEmail = req.user.email;
        const doc = await adminDb.collection('dashboards').doc(req.params.id).get();
        if (!doc.exists) return res.status(404).json({ success: false, message: 'Dashboard not found' });

        const data = doc.data();
        if (data.contractorEmail !== userEmail) {
            return res.status(403).json({ success: false, message: 'Access denied' });
        }
        if (data.status !== 'approved') {
            return res.status(403).json({ success: false, message: 'Dashboard not approved' });
        }

        // For PDF report type, redirect to the stored PDF
        if (data.reportType === 'pdf' && data.pdfReport && data.pdfReport.storagePath) {
            const bucket = storage.bucket();
            const fileRef = bucket.file(data.pdfReport.storagePath);
            const [signedUrl] = await fileRef.getSignedUrl({ action: 'read', expires: Date.now() + 7 * 24 * 60 * 60 * 1000 });
            return res.redirect(signedUrl);
        }

        // For HTML or auto report types, generate a comprehensive structured PDF
        const title = data.title || 'Analytics Report';
        const pdfDoc = new PDFDocument({ size: 'A4', margin: 40, info: { Title: title, Author: 'SteelConnect Analytics' }, bufferPages: true });

        const safeTitle = title.replace(/[^a-zA-Z0-9_\- ]/g, '').trim() || 'Report';
        const filename = `${safeTitle}_${new Date().toISOString().slice(0, 10)}.pdf`;

        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
        pdfDoc.pipe(res);

        // Colors matching the HTML dashboard theme
        const colors = {
            headerBg: '#0f172a',
            headerAccent: '#6366f1',
            primary: '#1e293b',
            accent: '#6366f1',
            success: '#10b981',
            warning: '#f59e0b',
            danger: '#ef4444',
            info: '#3b82f6',
            textDark: '#0f172a',
            textMed: '#334155',
            textLight: '#64748b',
            bgLight: '#f8fafc',
            bgCard: '#f1f5f9',
            border: '#e2e8f0',
            white: '#ffffff'
        };
        const pageWidth = 515; // 595 - 40*2 margins

        // Load template data
        let templateData = data.templateData || null;
        if (!templateData && data.storagePath) {
            try {
                const bucket = storage.bucket();
                const fileRef = bucket.file(data.storagePath);
                const [fileBuffer] = await fileRef.download();
                const fileName = data.fileName || 'file.xlsx';
                const sheets = parseSpreadsheet(fileBuffer, fileName);
                templateData = {};
                for (const [name, rows] of Object.entries(sheets)) {
                    templateData[name] = rows.slice(0, 500);
                }
            } catch (e) {
                console.error('[PDF-GEN] Failed to parse spreadsheet:', e.message);
            }
        }
        if (!templateData && data.googleSheetUrl) {
            try {
                const result = await fetchSheetData(data.googleSheetUrl);
                templateData = {};
                for (const [name, rows] of Object.entries(result.sheets)) {
                    templateData[name] = rows.slice(0, 500);
                }
            } catch (e) {
                console.error('[PDF-GEN] Failed to fetch sheet data:', e.message);
            }
        }

        // Helper: check page space and add new page if needed
        let yPos = 0;
        const ensureSpace = (needed) => {
            if (yPos + needed > 780) { pdfDoc.addPage(); yPos = 40; }
        };

        // Helper: draw a rounded rect (simulated with rect since PDFKit doesn't have roundedRect with fill easily)
        const drawCard = (x, y, w, h, bgColor) => {
            pdfDoc.save();
            pdfDoc.roundedRect(x, y, w, h, 6).fill(bgColor);
            pdfDoc.restore();
        };

        // ==================== COVER PAGE ====================
        // Full header banner
        pdfDoc.rect(0, 0, 595, 140).fill(colors.headerBg);
        // Accent stripe
        pdfDoc.rect(0, 130, 595, 10).fill(colors.headerAccent);

        // Title
        pdfDoc.fillColor(colors.white).fontSize(26).font('Helvetica-Bold')
            .text(title, 40, 35, { width: pageWidth });

        // Subtitle / description
        if (data.description) {
            pdfDoc.fillColor('#94a3b8').fontSize(11).font('Helvetica')
                .text(data.description, 40, pdfDoc.y + 4, { width: pageWidth });
        }

        // Report metadata badges
        yPos = 160;
        const genDate = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
        const freq = (data.frequency || 'daily').charAt(0).toUpperCase() + (data.frequency || 'daily').slice(1);

        drawCard(40, yPos, pageWidth, 50, colors.bgLight);
        pdfDoc.fillColor(colors.textLight).fontSize(8).font('Helvetica').text('GENERATED', 55, yPos + 8);
        pdfDoc.fillColor(colors.textDark).fontSize(10).font('Helvetica-Bold').text(genDate, 55, yPos + 20);
        pdfDoc.fillColor(colors.textLight).fontSize(8).font('Helvetica').text('FREQUENCY', 300, yPos + 8);
        pdfDoc.fillColor(colors.textDark).fontSize(10).font('Helvetica-Bold').text(freq, 300, yPos + 20);
        pdfDoc.fillColor(colors.textLight).fontSize(8).font('Helvetica').text('TYPE', 440, yPos + 8);
        pdfDoc.fillColor(colors.accent).fontSize(10).font('Helvetica-Bold').text((data.reportType || 'auto').toUpperCase(), 440, yPos + 20);
        yPos += 70;

        // ==================== SUMMARY METRICS (from template data) ====================
        if (templateData && Object.keys(templateData).length > 0) {
            // Extract key metrics from the data for a summary section
            const allSheetNames = Object.keys(templateData);
            let totalRows = 0;
            let totalColumns = 0;
            const numericSummaries = [];

            for (const [sheetName, rows] of Object.entries(templateData)) {
                if (!rows || rows.length === 0) continue;
                totalRows += rows.length;
                const headers = Object.keys(rows[0] || {});
                totalColumns += headers.length;

                // Find numeric columns and compute summaries
                headers.forEach(h => {
                    const numericVals = rows.map(r => parseFloat(r[h])).filter(v => !isNaN(v));
                    if (numericVals.length > rows.length * 0.5) { // At least 50% numeric
                        const sum = numericVals.reduce((a, b) => a + b, 0);
                        const avg = sum / numericVals.length;
                        const max = Math.max(...numericVals);
                        const min = Math.min(...numericVals);
                        numericSummaries.push({ sheet: sheetName, column: h, sum, avg, max, min, count: numericVals.length });
                    }
                });
            }

            // Summary cards row
            ensureSpace(80);
            pdfDoc.fillColor(colors.primary).fontSize(14).font('Helvetica-Bold').text('Report Overview', 40, yPos);
            yPos += 22;

            const cardWidth = Math.floor((pageWidth - 30) / 4);
            const summaryCards = [
                { label: 'Data Sheets', value: allSheetNames.length.toString(), color: colors.accent },
                { label: 'Total Records', value: totalRows.toLocaleString(), color: colors.success },
                { label: 'Data Fields', value: totalColumns.toString(), color: colors.info },
                { label: 'Metrics Found', value: numericSummaries.length.toString(), color: colors.warning }
            ];

            summaryCards.forEach((card, idx) => {
                const cx = 40 + idx * (cardWidth + 10);
                drawCard(cx, yPos, cardWidth, 52, colors.bgCard);
                pdfDoc.fillColor(colors.textLight).fontSize(7.5).font('Helvetica').text(card.label.toUpperCase(), cx + 10, yPos + 8, { width: cardWidth - 20 });
                pdfDoc.fillColor(card.color).fontSize(18).font('Helvetica-Bold').text(card.value, cx + 10, yPos + 22, { width: cardWidth - 20 });
            });
            yPos += 72;

            // Key metrics summary (top numeric columns)
            if (numericSummaries.length > 0) {
                ensureSpace(120);
                pdfDoc.fillColor(colors.primary).fontSize(14).font('Helvetica-Bold').text('Key Metrics Summary', 40, yPos);
                yPos += 22;

                const topMetrics = numericSummaries.slice(0, 8);
                const metricCardW = Math.floor((pageWidth - 10) / 2);

                topMetrics.forEach((metric, idx) => {
                    if (idx % 2 === 0) ensureSpace(55);
                    const cx = 40 + (idx % 2) * (metricCardW + 10);
                    const cy = yPos;

                    drawCard(cx, cy, metricCardW, 48, colors.bgLight);
                    // Metric name
                    const displayName = metric.column.length > 25 ? metric.column.substring(0, 25) + '...' : metric.column;
                    pdfDoc.fillColor(colors.textDark).fontSize(9).font('Helvetica-Bold').text(displayName, cx + 10, cy + 6, { width: metricCardW - 20 });
                    // Metric values in a row
                    const formatNum = (n) => Number.isInteger(n) ? n.toLocaleString() : n.toLocaleString(undefined, { maximumFractionDigits: 2 });
                    pdfDoc.fillColor(colors.textLight).fontSize(7).font('Helvetica')
                        .text(`Sum: ${formatNum(metric.sum)}  |  Avg: ${formatNum(metric.avg)}  |  Min: ${formatNum(metric.min)}  |  Max: ${formatNum(metric.max)}`, cx + 10, cy + 22, { width: metricCardW - 20 });
                    pdfDoc.fillColor(colors.textLight).fontSize(7).font('Helvetica')
                        .text(`Sheet: ${metric.sheet}  |  ${metric.count} values`, cx + 10, cy + 34, { width: metricCardW - 20 });

                    if (idx % 2 === 1) yPos += 58;
                });
                if (topMetrics.length % 2 === 1) yPos += 58;
                yPos += 10;
            }

            // ==================== DATA TABLES ====================
            for (const [sheetName, rows] of Object.entries(templateData)) {
                if (!rows || rows.length === 0) continue;
                const headers = Object.keys(rows[0] || {});
                if (headers.length === 0) continue;

                ensureSpace(80);

                // Section header with accent bar
                pdfDoc.rect(40, yPos, 4, 20).fill(colors.accent);
                pdfDoc.fillColor(colors.primary).fontSize(13).font('Helvetica-Bold')
                    .text(sheetName, 52, yPos + 2);
                pdfDoc.fillColor(colors.textLight).fontSize(8).font('Helvetica')
                    .text(`${rows.length} records · ${headers.length} columns`, 52, yPos + 17);
                yPos += 36;

                // Draw table - use all available width, limit columns to fit
                const maxCols = Math.min(headers.length, 8);
                const displayHeaders = headers.slice(0, maxCols);
                const colWidth = Math.floor(pageWidth / maxCols);
                const tableWidth = colWidth * maxCols;

                // Table header row
                pdfDoc.rect(40, yPos, tableWidth, 22).fill(colors.headerBg);
                displayHeaders.forEach((h, i) => {
                    pdfDoc.fillColor(colors.white).fontSize(7.5).font('Helvetica-Bold')
                        .text(String(h).substring(0, 20), 44 + (i * colWidth), yPos + 6, { width: colWidth - 8 });
                });
                yPos += 24;

                // Table rows
                const maxRows = Math.min(rows.length, 50);
                for (let r = 0; r < maxRows; r++) {
                    ensureSpace(18);
                    if (r % 2 === 0) {
                        pdfDoc.rect(40, yPos, tableWidth, 17).fill(colors.bgLight);
                    }
                    displayHeaders.forEach((h, i) => {
                        const val = rows[r][h];
                        const displayVal = val !== null && val !== undefined ? String(val).substring(0, 24) : '';
                        pdfDoc.fillColor(colors.textMed).fontSize(7).font('Helvetica')
                            .text(displayVal, 44 + (i * colWidth), yPos + 4, { width: colWidth - 8 });
                    });
                    yPos += 17;
                }

                // Row count indicator
                if (rows.length > maxRows) {
                    pdfDoc.fillColor(colors.textLight).fontSize(7.5).font('Helvetica-Oblique')
                        .text(`Showing ${maxRows} of ${rows.length} records`, 40, yPos + 4);
                    yPos += 16;
                }

                yPos += 20;
            }
        }

        // ==================== CHARTS SECTION ====================
        if (data.charts && data.charts.length > 0) {
            ensureSpace(60);
            pdfDoc.rect(40, yPos, 4, 20).fill(colors.warning);
            pdfDoc.fillColor(colors.primary).fontSize(14).font('Helvetica-Bold').text('Charts & Visualizations', 52, yPos + 2);
            yPos += 32;

            data.charts.forEach((chart, idx) => {
                ensureSpace(80);

                const chartTitle = chart.title || `Chart ${idx + 1}`;
                const chartType = (chart.type || 'bar').charAt(0).toUpperCase() + (chart.type || 'bar').slice(1);

                // Chart card
                drawCard(40, yPos, pageWidth, 65, colors.bgLight);
                pdfDoc.fillColor(colors.textDark).fontSize(11).font('Helvetica-Bold')
                    .text(`${idx + 1}. ${chartTitle}`, 55, yPos + 8, { width: pageWidth - 30 });
                pdfDoc.fillColor(colors.accent).fontSize(8).font('Helvetica')
                    .text(`Chart Type: ${chartType}`, 55, yPos + 24);

                // Data summary inside chart card
                if (chart.labels && chart.labels.length > 0 && chart.datasets && chart.datasets.length > 0) {
                    const ds = chart.datasets[0];
                    const dataItems = chart.labels.slice(0, 10).map((label, i) => {
                        const val = ds.data && ds.data[i] !== undefined ? ds.data[i] : '-';
                        return `${label}: ${val}`;
                    }).join('  ·  ');
                    pdfDoc.fillColor(colors.textMed).fontSize(7).font('Helvetica')
                        .text(dataItems, 55, yPos + 38, { width: pageWidth - 30 });
                }

                yPos += 75;
            });
        }

        // ==================== PREDICTIVE ANALYSIS ====================
        if (data.predictiveAnalysis) {
            const pa = data.predictiveAnalysis;
            ensureSpace(60);

            pdfDoc.rect(40, yPos, 4, 20).fill(colors.success);
            pdfDoc.fillColor(colors.primary).fontSize(14).font('Helvetica-Bold').text('Predictive Analysis', 52, yPos + 2);
            yPos += 32;

            if (pa.summary) {
                ensureSpace(40);
                drawCard(40, yPos, pageWidth, 'auto');
                pdfDoc.fillColor(colors.textMed).fontSize(10).font('Helvetica')
                    .text(pa.summary, 50, yPos, { width: pageWidth - 20 });
                yPos = pdfDoc.y + 16;
            }

            // Key insights
            if (pa.insights && pa.insights.length > 0) {
                ensureSpace(30);
                pdfDoc.fillColor(colors.success).fontSize(11).font('Helvetica-Bold').text('Key Insights', 50, yPos);
                yPos += 18;

                pa.insights.forEach(insight => {
                    ensureSpace(20);
                    const insightText = typeof insight === 'string' ? insight : (insight.text || insight.title || JSON.stringify(insight));
                    drawCard(50, yPos, pageWidth - 20, 'auto');
                    pdfDoc.fillColor(colors.success).fontSize(9).font('Helvetica').text('●', 54, yPos + 1);
                    pdfDoc.fillColor(colors.textMed).fontSize(9).font('Helvetica')
                        .text(insightText, 68, yPos, { width: pageWidth - 48 });
                    yPos = pdfDoc.y + 8;
                });
                yPos += 8;
            }

            // Predictions
            if (pa.predictions && pa.predictions.length > 0) {
                ensureSpace(30);
                pdfDoc.fillColor(colors.accent).fontSize(11).font('Helvetica-Bold').text('Predictions', 50, yPos);
                yPos += 18;

                pa.predictions.forEach(pred => {
                    ensureSpace(20);
                    const predText = typeof pred === 'string' ? pred : (pred.text || pred.description || JSON.stringify(pred));
                    pdfDoc.fillColor(colors.accent).fontSize(9).font('Helvetica').text('▸', 54, yPos + 1);
                    pdfDoc.fillColor(colors.textMed).fontSize(9).font('Helvetica')
                        .text(predText, 68, yPos, { width: pageWidth - 48 });
                    yPos = pdfDoc.y + 8;
                });
            }
        }

        // ==================== FOOTER ON EVERY PAGE ====================
        const totalPages = pdfDoc.bufferedPageRange().count;
        for (let i = 0; i < totalPages; i++) {
            pdfDoc.switchToPage(i);
            // Bottom bar
            pdfDoc.save();
            pdfDoc.rect(0, 805, 595, 37).fill(colors.bgLight);
            pdfDoc.fillColor(colors.textLight).fontSize(7).font('Helvetica')
                .text('Generated by SteelConnect Analytics Platform', 40, 812, { width: 400 });
            pdfDoc.fillColor(colors.textLight).fontSize(7).font('Helvetica')
                .text(`Page ${i + 1} of ${totalPages}`, 460, 812, { width: 95, align: 'right' });
            pdfDoc.restore();
        }

        pdfDoc.end();

        console.log(`[ANALYSIS] PDF report generated for dashboard ${req.params.id} by ${userEmail}`);
    } catch (error) {
        console.error('[ANALYSIS] PDF generation error:', error);
        if (!res.headersSent) {
            res.status(500).json({ success: false, message: 'Failed to generate PDF report' });
        }
    }
});

export default router;
