// src/services/dashboardSyncService.js
// Auto-sync service for linked sheet dashboards
// Periodically re-fetches data from Google Sheets / SharePoint links
// and updates dashboard charts when data changes

import { adminDb } from '../config/firebase.js';
import { fetchSheetData, autoGenerateDashboardConfig } from '../utils/sheetAnalyzer.js';

let syncIntervalHandle = null;
const SYNC_CHECK_INTERVAL = 15 * 60 * 1000; // Check every 15 minutes

// Sync interval mapping (how often each frequency should sync)
const FREQUENCY_INTERVALS = {
    'realtime': 5 * 60 * 1000,       // 5 minutes
    'hourly': 60 * 60 * 1000,         // 1 hour
    'daily': 24 * 60 * 60 * 1000,     // 24 hours
    'weekly': 7 * 24 * 60 * 60 * 1000, // 7 days
    'monthly': 30 * 24 * 60 * 60 * 1000, // 30 days
    'quarterly': 90 * 24 * 60 * 60 * 1000,
    'manual': Infinity                  // Never auto-sync
};

/**
 * Check if a dashboard needs syncing based on its syncInterval and lastSyncedAt
 */
function needsSync(dashboard) {
    const syncInterval = dashboard.syncInterval || 'manual';
    if (syncInterval === 'manual') return false;

    const intervalMs = FREQUENCY_INTERVALS[syncInterval] || Infinity;
    if (intervalMs === Infinity) return false;

    const lastSynced = dashboard.lastSyncedAt
        ? new Date(dashboard.lastSyncedAt).getTime()
        : 0;
    const now = Date.now();
    return (now - lastSynced) >= intervalMs;
}

/**
 * Sync a single dashboard — re-fetch data from its linked sheet
 * Returns true if data was updated, false if no changes
 */
async function syncDashboard(docId, dashboardData) {
    const sheetUrl = dashboardData.googleSheetUrl;
    if (!sheetUrl) return false;

    try {
        console.log(`[SYNC] Fetching data for dashboard ${docId} from: ${sheetUrl.substring(0, 60)}...`);

        const result = await fetchSheetData(sheetUrl);
        const newCharts = autoGenerateDashboardConfig(result.sheets, dashboardData.frequency || 'daily');

        if (newCharts.length === 0) {
            console.log(`[SYNC] No charts generated for dashboard ${docId}, skipping update`);
            await adminDb.collection('dashboards').doc(docId).update({
                lastSyncedAt: new Date().toISOString(),
                lastSyncStatus: 'no_data'
            });
            return false;
        }

        // Compare chart data to see if anything changed
        const oldChartHash = JSON.stringify((dashboardData.charts || []).map(c => c.datasets));
        const newChartHash = JSON.stringify(newCharts.map(c => c.datasets));
        const dataChanged = oldChartHash !== newChartHash;

        const updateData = {
            lastSyncedAt: new Date().toISOString(),
            lastSyncStatus: 'success',
            updatedAt: new Date().toISOString()
        };

        if (dataChanged) {
            updateData.charts = newCharts;
            updateData.sheetNames = result.sheetNames;
            updateData.rawData = result.sheets;
            updateData.syncDataChanged = true;
            console.log(`[SYNC] Dashboard ${docId} data CHANGED — updated ${newCharts.length} charts`);
        } else {
            updateData.syncDataChanged = false;
            console.log(`[SYNC] Dashboard ${docId} data unchanged`);
        }

        await adminDb.collection('dashboards').doc(docId).update(updateData);
        return dataChanged;

    } catch (error) {
        console.error(`[SYNC] Failed to sync dashboard ${docId}:`, error.message);
        await adminDb.collection('dashboards').doc(docId).update({
            lastSyncedAt: new Date().toISOString(),
            lastSyncStatus: 'error',
            lastSyncError: error.message
        });
        return false;
    }
}

/**
 * Run a sync check — find all dashboards that need syncing and process them
 */
async function runSyncCheck() {
    try {
        // Get all approved dashboards that have a linked sheet URL
        const snapshot = await adminDb.collection('dashboards')
            .where('status', '==', 'approved')
            .get();

        const toSync = [];
        snapshot.docs.forEach(doc => {
            const d = doc.data();
            if (d.googleSheetUrl && d.syncInterval && d.syncInterval !== 'manual') {
                if (needsSync(d)) {
                    toSync.push({ id: doc.id, data: d });
                }
            }
        });

        if (toSync.length === 0) return;

        console.log(`[SYNC] Found ${toSync.length} dashboard(s) needing sync`);

        let updated = 0;
        // Process sequentially to avoid rate limits
        for (const { id, data } of toSync) {
            const changed = await syncDashboard(id, data);
            if (changed) updated++;
            // Small delay between syncs to be nice to external APIs
            await new Promise(r => setTimeout(r, 2000));
        }

        console.log(`[SYNC] Sync check complete: ${updated}/${toSync.length} dashboards updated`);
    } catch (error) {
        console.error('[SYNC] Sync check error:', error.message);
    }
}

/**
 * Force sync a specific dashboard (called from API endpoint)
 */
export async function forceSyncDashboard(docId) {
    const doc = await adminDb.collection('dashboards').doc(docId).get();
    if (!doc.exists) throw new Error('Dashboard not found');

    const data = doc.data();
    if (!data.googleSheetUrl) throw new Error('Dashboard has no linked sheet URL');

    const changed = await syncDashboard(docId, data);
    return {
        success: true,
        dataChanged: changed,
        message: changed
            ? 'Dashboard synced — data has been updated with latest sheet data'
            : 'Dashboard synced — no changes detected in the sheet data'
    };
}

/**
 * Start the auto-sync background scheduler
 */
export function startAutoSync() {
    if (syncIntervalHandle) {
        console.log('[SYNC] Auto-sync already running');
        return;
    }

    console.log(`[SYNC] Starting auto-sync scheduler (checking every ${SYNC_CHECK_INTERVAL / 60000} minutes)`);
    syncIntervalHandle = setInterval(runSyncCheck, SYNC_CHECK_INTERVAL);

    // Run an initial check after 30 seconds (let server finish starting)
    setTimeout(runSyncCheck, 30000);
}

/**
 * Stop the auto-sync background scheduler
 */
export function stopAutoSync() {
    if (syncIntervalHandle) {
        clearInterval(syncIntervalHandle);
        syncIntervalHandle = null;
        console.log('[SYNC] Auto-sync scheduler stopped');
    }
}
