// src/models/Estimation.js

import mongoose from 'mongoose';

const estimationSchema = new mongoose.Schema({
    // Link to the user who created the estimation
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User', // Assumes you have a 'User' model
        required: true,
    },
    // Basic project info
    projectId: {
        type: String,
        required: true,
        trim: true,
    },
    location: {
        type: String,
        required: true,
    },
    // The detailed cost summary object from your EstimationEngine
    cost_summary: {
        type: mongoose.Schema.Types.Mixed, // Stores the complex summary object
        required: true,
    },
    // The line items generated by the estimation
    items: [{
        type: mongoose.Schema.Types.Mixed,
    }],
    // The category breakdown
    categories: {
        type: mongoose.Schema.Types.Mixed,
    },
    // AI-generated assumptions and exclusions
    assumptions: [String],
    exclusions: [String],
    // Overall confidence score from the AI
    confidence_score: {
        type: Number,
    },
    // Timestamps for creation and updates
    createdAt: {
        type: Date,
        default: Date.now,
    },
    updatedAt: {
        type: Date,
        default: Date.now,
    },
});

// Before saving, update the 'updatedAt' field
estimationSchema.pre('save', function(next) {
    this.updatedAt = Date.now();
    next();
});

const Estimation = mongoose.model('Estimation', estimationSchema);

export default Estimation;
